#+TITLE:       Mozilla Permits the Use of Multiple SHA-1 Certificates
#+AUTHOR:      Andrew L
#+EMAIL:       adlawren@onyx
#+DATE:        2018-05-04 Fri
#+URI:         /blog/2016/2/27/mozilla-permits-the-use-of-multiple-sha-1-certificates
#+KEYWORDS:    Vulnerability, Exploit, Encryption, SHA-1
#+TAGS:        Vulnerability, Exploit, Encryption
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Mozilla Permits the Use of Multiple SHA-1 Certificates

#+OPTIONS: \n:t

* TL;DR

Mozilla has recently made a controversial decision regarding the permitted use of SHA-1 certificates [1].

* Details

Mozilla, together with other organizations including Microsoft and Google, formally made the decision to deprecate support for SHA-1 certificates after the results of a research project were released [2] wherein the discovery was made that the SHA-1 encryption algorithm may be compromised using significantly fewer resources (both monetary and temporal) than previously hypothesized (10 days and a 64-GPU cluster specifically).

The research project involved the application of a technique which facilitated a greater degree of efficiency during the discovery of cryptographic collisions [3]; the occurrence of a common hash generated by more than one message [4]. Cryptographic collisions facilitate Digital Signature based attacks [4] wherein a digital signature is obtained, using a non-malicious document, and subsequently integrated into a malicious document which yields the same hash code as the non-malicious document. Consequently, the malicious document will be accepted during processing due to lack of distinguishability between the expected, non-malicious document and the malicious document.

Mozilla has recently permitted an exception to the original decision to deprecate the use of SHA-1 certificates. Symantec has been permitted to issue 9 SHA-1 certificates in order to remedy issues being experienced by Worldpay PLC, a payment processing company. Some of the SSL/TLS powered servers operated by Worldpay were in need of new SHA-1 certificates, for which requests were not issued before the specified deadline (January 1st, 2016) due to miscommunications. As a result, users of the payment service are subject to potentially experiencing misprocessed payments.

* Summary

Mozilla (and other browser developers alike) are operating in a difficult position in light of these circumstances; the compromise of the adopted policy to reject SHA-1 certificates may lead to further leniency in similar situations. However, the operability of a critical service may be affected by the decision to uphold the deprecation policy.

* Sources:

